submission:
  # Model configuration
  regime_thresholds:
    high_vol: 1.5
    low_vol: 0.5
  
  # Position sizing
  max_position: 1.0
  min_confidence: 0.2
  
  # Risk controls
  max_leverage: 5.0
  max_concentration: 0.2
  
  # Performance monitoring
  track_metrics: true
  log_predictions: true 